all:
  hosts:
    login-node:
      ansible_host: 1.3.3.7
      ansible_user: sysadmin

  children:
    compute-nodes:
      hosts:
        compute-node-01:
          ansible_host: 10.0.0.1
          ansible_user: root
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sysadmin@1.3.3.7"'
        compute-node-02:
          ansible_host: 10.0.0.2
          ansible_user: root
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sysadmin@1.3.3.7"'  
